APPROVED_COOKING_METHODS = [
    ("air_fry", "air fry"),
    ("combi_oven", "combi oven"),
    ("no_cooking", "no cooking"),
    ("bake", "bake"),
    ("barbecue", "barbecue"),
    ("blanch", "blanch"),
    ("braise", "braise"),
    ("boil", "boil"),
    ("brown", "brown"),
    ("caramelize", "caramelize"),
    ("charbroil", "charbroil"),
    ("fry", "fry"),
    ("griddle", "griddle"),
    ("grill", "grill"),
    ("pan_sear", "pan sear"),
    ("par_boil", "par boil"),
    ("reduce", "reduce"),
    ("roast", "roast"),
    ("saute", "saute"),
    ("simmer", "simmer"),
    ("smoke", "smoke"),
    ("steam", "steam"),
    ("stew", "stew"),
    ("stir_fry", "stir fry"),
    ("sweat", "sweat"),
]

COOKING_METHOD_LABELS = dict(APPROVED_COOKING_METHODS)
